apiVersion: v1
kind: Namespace
metadata:
  name: prometheus-node-exporter
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-node-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prometheus-node-exporter
  project: incubator
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-node-exporter
    targetRevision: HEAD
    helm:
      releaseName: prometheus-node-exporter
      valuesObject:
        service:
          enabled: true
          type: ClusterIP
          port: 9100
          targetPort: 9100
          nodePort:
          portName: metrics
          listenOnAllInterfaces: true
          annotations:
            prometheus.io/scrape: "true"
        # Set a NetworkPolicy with:
        # ingress only on service.port
        # no egress permitted
        networkPolicy:
          enabled: true
